= Deploying f8toggle services on Minishift

== Pre-requisites
* Install https://docs.openshift.org/latest/minishift/getting-started/installing.html[Minishift]
* Install OpenShift command oc
* Start minishift
```
minishift start --memory=7000 --cpus=4 --disk-size=50g
```
on macOS:
```
minishift start --vm-driver=xhyve --memory=7000 --cpus=4 --disk-size=50g
```
* Point `oc` to Minishift
```
oc config use-context minishift
oc login -u developer:developer
```

== Let's deploy `fabric8-toggles` server in OpenShift

Our ` fabric8-toggles` server needs a postgres database and a nodejs server.
We're going to deploy our server in dev mode using minishift.

Let's start with...

=== Deploy database

We're going to deploy  a postgres database using a template that fetch an already built image for you.

Once you have installed `minishift` and `oc`, run the following commands to create all deployments, replica sets, pods and services in the default namespace:
```
# create project
oc new-project f8toggles
# f8toggle database
oc create -f f8toggle-db-deployment.yml
# f8toggle database service
oc create -f f8toggle-db-service.yml
```

Once all scripts passed, the minishift objects will be available:
```
> oc get all
dc/f8toggle-db   1          1         1         config
rc/f8toggle-db-1   1         1         1         16s
svc/f8toggle-db   172.30.5.173   <none>        5432/TCP   8s
po/f8toggle-db-1-0rtkj   1/1       Running   0          14s
```

=== Build the docker image for the JS server

> Note: you can skip this step by pulling an existing image, in fabric8-toggles-deployment.yml 
change `image: 172.30.1.1:5000/f8toggles/fabric8togglesdocker:latest`
to `image: registry.devshift.net/fabric8-services/fabric8-toggles:latest`

Using the https://medium.com/@xcoulon/tips-for-minikube-minishift-users-including-myself-accessing-the-clusters-docker-deamon-c15032a60b08[the cluster’s Docker deamon], 
we're going to build the docker image and make it available directly inside the minishift local registry. 
Go to the ../../Dockerfile[Dockerfile] folder and type:
```
cd path_to_where_you_clone_https://github.com/fabric8-services/fabric8-toggles
eval $(minishift docker-env)
docker login -u developer -p $(oc whoami -t) $(minishift openshift registry)
docker build -t fabric8togglesdocker:latest .
docker tag fabric8togglesdocker $(minishift openshift registry)/f8toggles/fabric8togglesdocker
docker push $(minishift openshift registry)/f8toggles/fabric8togglesdocker
```
We will use `fabric8togglesdocker:latest` in our deployment script.
Let's deploy...

=== Deploy the nodejs server

```
# back to .make/.minishift directory
cd .make/.minishift/
# fabric8-toggles (nodejs server) deployment
oc create -f fabric8-toggles-deployment.yml
# fabric8-toggles (nodejs server) service
oc create -f fabric8-toggles-service.yml
# create route to access
oc create -f fabric8-toggles-route.yml 
```

> NOTE: It might happen that `nip.io` is unavailabile. When you create route for an application 
running in OpenShift (provided by Minishift) it uses nip.io for routing to the Minishift VM IP 
address. As a result it is impossible to access the route created with nip.io suffix.
As a alternative you can try using `xip.io`. Here the steps for using xip.io in Minishift 
instead of nip.io.
* Get the IP address of the Minishift VM 
$ minishift ip
To set the routing suffix to xip.io, run the following command after IP-ADDRESS with actual IP address you found from previous command.
$ minishift openshift config set --patch '{"routingConfig": {"subdomain": "<IP-ADDRESS>.xip.io"}}'

Once the nodejs server is deployed, the data base is bootstrapped by the server.  
You can verify DB schema was created at server start-up:

```
oc rsh f8toggle-db-2-8zrhk
psql -h localhost -d unleashdb -U user
unleashdb=> \dt+
                            List of relations
 Schema |        Name         | Type  | Owner |    Size    | Description 
--------+---------------------+-------+-------+------------+-------------
 public | client_applications | table | user  | 8192 bytes | 
 public | client_instances    | table | user  | 8192 bytes | 
 public | client_metrics      | table | user  | 8192 bytes | 
 public | events              | table | user  | 16 kB      | 
 public | features            | table | user  | 16 kB      | 
 public | migrations          | table | user  | 8192 bytes | 
 public | strategies          | table | user  | 16 kB      | 
(7 rows)
```

Once the route is created, go to f8toggle admin console:

http://fabric8-toggles-f8toggles.<YOUR_IP>.nip.io (as displayed in your minishit console).
where: 
* <YOUR_IP> could be find out by `minishift ip`. (it's also display in the log with the `minishift start`command)
* use developer /developer as username / password

If something goes wrong, to check logs:
```
oc logs -f fabric8-toggles-1-vvtm2
```
where fabric8-toggles-1-vvtm2 is your ephemeral pod id.

=== Build the docker image for the fabric8-toggles-service the client

> Note: you can skip this step by pulling an existing image, in fabric8-toggles-service-deployment.yml
change `image: 172.30.1.1:5000/f8toggles/fabric8togglesdocker:latest`
to `image: registry.devshift.net/fabric8-services/fabric8-toggles-service:latest`

Using the https://medium.com/@xcoulon/tips-for-minikube-minishift-users-including-myself-accessing-the-clusters-docker-deamon-c15032a60b08[the cluster’s Docker deamon],
we're going to build the docker image and make it available directly inside the minishift local registry.
Go to the path where you clone https://github.com/fabric8-services/fabric8-toggles-service and type:

```
# build locally on your host targetting linux env for final go binary
make clean deps generate
make build-linux
# use Docker daemon from minishift
eval $(minishift docker-env)
# build deployment image using linux binary
make docker-image-deploy-linux
# push to minishift docker hub
docker tag fabric8-toggles-service-deploy $(minishift openshift registry)/f8toggles/fabric8togglesservicedocker
docker login -u developer -p $(oc whoami -t) $(minishift openshift registry)
docker push $(minishift openshift registry)/f8toggles/fabric8togglesservicedocker
```
We will use `fabric8togglesservicedocker:latest` in our deployment script.
Let's deploy...


=== Deploy the fabric8-toggles-service, the client service

In `fabric8-toggles-config.yml` change the value of `fabric8.toggles.url` to match the URL you've just deployed in minishift.
```
# back to .make/.minishift directory
cd .make/.minishift/
# use config map
oc create -f fabric8-toggles-config.yml
# fabric8-toggles-service deployment
oc create -f fabric8-toggles-service-deployment.yml
# fabric8-toggles-service service
oc create -f fabric8-toggles-service-service.yml
# create route to access
oc create -f fabric8-toggles-service-route.yml
```

To check id correctly deployed:
```
> curl http://fabric8-toggles-service-f8toggles.<YOUR_IP>.nip.io/api/features/Planner
{"errors":[{"code":"jwt_security_error","detail":"missing header \"Authorization\"","id":"VU1H/HOa","status":"401","title":"Unauthorized"}]}
```
