# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# make sure the goagen tools are available for generating the controllers
required = [
    "github.com/goadesign/goa/cors",
    "github.com/goadesign/goa/encoding/form",
    "github.com/goadesign/goa/goagen",
    "github.com/goadesign/goa/goagen/codegen",
    "github.com/goadesign/goa/goagen/gen_app",
    "github.com/goadesign/goa/goagen/gen_controller",
    "github.com/goadesign/goa/goagen/gen_swagger",
    "github.com/goadesign/goa/goagen/gen_client",
    "github.com/goadesign/goa/goagen/utils",
    "github.com/goadesign/goa/goatest",
    "github.com/fabric8-services/fabric8-auth/design",
    "github.com/gojuno/minimock/cmd/minimock",
    ]

ignored = [
  "github.com/fabric8-services/fabric8-toggles-service/app", 
  "github.com/fabric8-services/fabric8-toggles-service/auth/client", 
  "github.com/fabric8-services/fabric8-toggles-service/feature"]

[[constraint]]
  name = "github.com/Unleash/unleash-client-go"
  source = "https://github.com/xcoulon/unleash-client-go"
  revision = "1d017a5259cd8ebcaa17c83e7662a635383e555f"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "github.com/dnaeon/go-vcr"
  revision= "9d71b8a6df86e00127f96bc8dabc09856ab8afdb"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-auth"
  revision = "f49fbf645355af271893af5d54ac1abbcdaf378f"

[[constraint]]
  name = "github.com/gojuno/minimock"
  branch = "master"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "v2.1.3"

[prune]
  go-tests = true
  unused-packages = true
