== Deployment on Minishift

=== Pre-requisites
* Install https://docs.openshift.org/latest/minishift/getting-started/installing.html[Minishift]
* Install OpenShift command oc
* Install https://github.com/kedgeproject/kedge/blob/master/docs/installation.md[Kedge]
* Start minishift
```
minishift start --memory=7000 --cpus=4 --disk-size=50g
```
on macOS:
```
minishift start --vm-driver=xhyve --memory=7000 --cpus=4 --disk-size=50g
```
* Point `oc` to Minishift
```
oc config use-context minishift
oc login -u developer -p developer
```

=== Deploy `toggles` and `toggles-service` server in Minishift using makefile

TL;DR: To deploy both `toggles` server and `toggle-services` client run:

```
minishift start --memory=7000 --cpus=4 --disk-size=50g
make login
make deploy-toggles
male deploy-toggles-service
```

=== Long story: step by step deployment

Our ` fabric8-toggles` server needs a postgres database and a nodejs server.
We're going to deploy our server in dev mode using minishift.

Let's start with...

==== Deploy database

We're going to deploy  a postgres database using a template that fetch an already built image for you.

Once you have installed `minishift` and `oc`, run the following commands to create all deployments, replica sets, pods and services in the default namespace:
```
# create project
oc new-project fabric8
# deployment configuration, service for toggles-db
kedge apply -f toggles-db.yml
```

Once all scripts passed, the minishift objects will be available:
```
> oc get all
dc/f8toggle-db   1          1         1         config
rc/f8toggle-db-1   1         1         1         16s
svc/f8toggle-db   172.30.5.173   <none>        5432/TCP   8s
po/f8toggle-db-1-0rtkj   1/1       Running   0          14s
```

> Note: By default we build from CentOS CI image. You can change that in `toggles.yml`.

==== Deploy the nodejs server

```
# back to minishift directory
cd minishift/
# deployment configuration, service for toggles
kedge apply -f toggles.yml
# create route to access
oc expose svc toggles
```

> NOTE: It might happen that `nip.io` is unavailabile. When you create route for an application
running in OpenShift (provided by Minishift) it uses nip.io for routing to the Minishift VM IP
address. As a result it is impossible to access the route created with nip.io suffix.
As a alternative you can try using `xip.io`. Here the steps for using xip.io in Minishift
instead of nip.io.
* Get the IP address of the Minishift VM
$ minishift ip
To set the routing suffix to xip.io, run the following command after IP-ADDRESS with actual IP address you found from previous command.
$ minishift openshift config set --patch '{"routingConfig": {"subdomain": "<IP-ADDRESS>.xip.io"}}'

Once the nodejs server is deployed, the data base is bootstrapped by the server.
You can verify DB schema was created at server start-up:

```
oc rsh f8toggle-db-2-8zrhk
psql -h localhost -d unleashdb -U user
unleashdb=> \dt+
                            List of relations
 Schema |        Name         | Type  | Owner |    Size    | Description
--------+---------------------+-------+-------+------------+-------------
 public | client_applications | table | user  | 8192 bytes |
 public | client_instances    | table | user  | 8192 bytes |
 public | client_metrics      | table | user  | 8192 bytes |
 public | events              | table | user  | 16 kB      |
 public | features            | table | user  | 16 kB      |
 public | migrations          | table | user  | 8192 bytes |
 public | strategies          | table | user  | 16 kB      |
(7 rows)
```

Once the route is created, go to f8toggle admin console:

http://fabric8-toggles-fabric8.<YOUR_IP>.nip.io (as displayed in your minishit console).
where:
* <YOUR_IP> could be find out by `minishift ip`. (it's also display in the log with the `minishift start`command)
* use developer /developer as username / password

If something goes wrong, to check logs:
```
oc logs -f fabric8-toggles-1-vvtm2
```
where fabric8-toggles-1-vvtm2 is your ephemeral pod id.

> Note: By default we build from your source.
By changing `toggles-service.yml` the line: `image: push.registry.devshift.net/fabric8-services/fabric8-toggles-service:latest`
to `image: registry.devshift.net/fabric8-services/fabric8-toggles-service:latest` you can point to CentOS CI.

==== Deploy the fabric8-toggles-service, the client service

Run the commands:
```
# back to minishift directory
cd minishift/
# export env variables
export F8_AUTH_URL=https://auth.prod-preview.openshift.io
export F8_TOGGLES_URL=http://toggles:4242/api
export F8_KEYCLOAK_URL=https://sso.prod-preview.openshift.io
# deployment configuration, service for toggles-service.
kedge apply -f toggles-service.yml
# create route to access
oc expose svc toggles-service
```

To check id correctly deployed:
```
> curl http://fabric8-toggles-service-fabric8.<YOUR_IP>.nip.io/api/features/Planner
{"errors":[{"code":"jwt_security_error","detail":"missing header \"Authorization\"","id":"VU1H/HOa","status":"401","title":"Unauthorized"}]}
```
