kind: Template
apiVersion: v1
metadata:
  name: auth
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
    labels:
      service: f8toggles-service
    name: f8toggles-service
  spec:
    replicas: 2
    selector:
      service: f8toggles-service
    template:
      metadata:
        labels:
          service: f8toggles-service
      spec:
        containers:
        - env:
          - name: F8_AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: f8toggles-service
                key: auth.url
          - name: F8_TOGGLES_URL
            valueFrom:
              configMapKeyRef:
                name: f8toggles-service
                key: toggles.url
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: f8toggles-service
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 0.4m
              memory: 15Mi
            limits:
              cpu: 400m
              memory: 1Gi            
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: f8toggles-service
    labels:
      service: f8toggles-service
  spec:
    ports:
      - name: "80"
        protocol: TCP
        port: 80
        targetPort: 8080
    selector:
      service: f8toggles-service
    type: ClusterIP
    sessionAffinity: null
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-fabric8-services-fabric8-toggles-service
- name: IMAGE_TAG
  value: latest
